name: Push to Hugging Face Hub
on:
  workflow_dispatch: # Manual trigger
jobs:
  push:
    runs-on: ubuntu-latest
    env:
      HUGGINGFACE_TOKEN: ${{ secrets.HUGGINGFACE_TOKEN }}
      WANDB_API_KEY: ${{ secrets.WANDB_API_KEY }}
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.10.12"
      - name: Install dependencies
        run: |
          pip install huggingface_hub
      - name: Push Model to Hugging Face
        run: python src/push_to_hf.py
